### ISSUE TITLE
Flow is `null` but `InternalLifecycleIntegration` exists after process death, this results in NPE in `getSystemService` integration

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/flowless#25]
Caused by: java.lang.NullPointerException
                                                                                    at flowless.InternalContextWrapper.getSystemService(InternalContextWrapper.java:69)
                                                                                    at flowless.ServiceProvider.get(ServiceProvider.java:22)
                                                                                    at com.zhuinden.examplegithubclient.presentation.activity.main.MainActivity.getSystemService(MainActivity.java:156)
                                                                                    at android.view.ViewConfiguration.<init>(ViewConfiguration.java:282)
                                                                                    at android.view.ViewConfiguration.get(ViewConfiguration.java:323)
                                                                                    at android.view.View.<init>(View.java:3236)
                                                                                    at android.view.ViewGroup.<init>(ViewGroup.java:420)
                                                                                    at android.widget.FrameLayout.<init>(FrameLayout.java:93)

**Comment by Zhuinden** [comment]
Fixed by https://github.com/Zhuinden/flowless/commit/15e5af663134a3e8420f94d8a956f1f33bd60e94
